apiVersion: v1
kind: ReplicationController
metadata: 
  name: myreplica
  labels:
    name: replicaTest
    teir: frontend
spec:
  template:
    metadata: 
      name: nginx
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  